<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Article;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use PHPUnit\Framework\Attributes\Test;

/**
 * ArticleControllerTest
 *
 * Feature tests for ArticleController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller ArticleSchema --test
 */
class ArticleControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /articles ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        $user = User::factory()->create();
        $this->actingAs($user);
        Article::factory()->for($user)->create();
        Article::factory()->for($user)->create();

        $response = $this->getJson('/articles');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /articles ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_article(): void
    {
        $user = User::factory()->create();
        $this->actingAs($user);
        $data = Arr::only(Article::factory()->make()->toArray(), ['title', 'slug', 'content', 'excerpt', 'status', 'published_at']);

        $response = $this->postJson('/articles', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Article)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $user = User::factory()->create();
        $this->actingAs($user);
        $response = $this->postJson('/articles', []);

        $response->assertUnprocessable();
    }

    // ── GET /articles/{article} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_article(): void
    {
        $user = User::factory()->create();
        $this->actingAs($user);
        $article = Article::factory()->for($user)->create();

        $response = $this->getJson("/articles/{$article->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $article->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_article(): void
    {
        $this->getJson('/articles/999999')->assertNotFound();
    }

    // ── PUT /articles/{article} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_article(): void
    {
        $user = User::factory()->create();
        $this->actingAs($user);
        $article  = Article::factory()->for($user)->create();
        $data = Arr::only(Article::factory()->make()->toArray(), ['title', 'slug', 'content', 'excerpt', 'status', 'published_at']);

        $response = $this->putJson("/articles/{$article->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $article->id]);
    }

    // ── DELETE /articles/{article} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_article(): void
    {
        $user = User::factory()->create();
        $this->actingAs($user);
        $article = Article::factory()->for($user)->create();

        $this->deleteJson("/articles/{$article->id}")->assertOk();

        $this->assertSoftDeleted((new Article)->getTable(), ['id' => $article->id]);
    }


    // ── Soft delete / restore ──────────────────────────────────────────────────

    #[Test]
    public function restore_recovers_a_soft_deleted_article(): void
    {
        $user = User::factory()->create();
        $this->actingAs($user);
        $article = Article::factory()->for($user)->create();
        $article->delete();

        $this->patchJson("/articles/restore/{$article->id}")->assertOk();

        $this->assertNotSoftDeleted((new Article)->getTable(), ['id' => $article->id]);
    }
}