<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Discount;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * DiscountControllerTest
 *
 * Feature tests for DiscountController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller DiscountSchema --test
 */
class DiscountControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /discounts ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Discount::factory()->create();
        Discount::factory()->create();

        $response = $this->getJson('/discounts');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /discounts ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_discount(): void
    {
        $data = Discount::factory()->make()->toArray();

        $response = $this->postJson('/discounts', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Discount)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/discounts', []);

        $response->assertUnprocessable();
    }

    // ── GET /discounts/{discount} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_discount(): void
    {
        $discount = Discount::factory()->create();

        $response = $this->getJson("/discounts/{$discount->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $discount->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_discount(): void
    {
        $this->getJson('/discounts/999999')->assertNotFound();
    }

    // ── PUT /discounts/{discount} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_discount(): void
    {
        $discount  = Discount::factory()->create();
        $data = Discount::factory()->make()->toArray();

        $response = $this->putJson("/discounts/{$discount->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $discount->id]);
    }

    // ── DELETE /discounts/{discount} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_discount(): void
    {
        $discount = Discount::factory()->create();

        $this->deleteJson("/discounts/{$discount->id}")->assertOk();

        $this->assertDatabaseMissing((new Discount)->getTable(), ['id' => $discount->id]);
    }

}