<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Employee;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * EmployeeControllerTest
 *
 * Feature tests for EmployeeController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller EmployeeSchema --test
 */
class EmployeeControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /employees ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Employee::factory()->create();
        Employee::factory()->create();

        $response = $this->getJson('/employees');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /employees ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_employee(): void
    {
        $data = Employee::factory()->make()->toArray();

        $response = $this->postJson('/employees', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Employee)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/employees', []);

        $response->assertUnprocessable();
    }

    // ── GET /employees/{employee} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_employee(): void
    {
        $employee = Employee::factory()->create();

        $response = $this->getJson("/employees/{$employee->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $employee->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_employee(): void
    {
        $this->getJson('/employees/999999')->assertNotFound();
    }

    // ── PUT /employees/{employee} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_employee(): void
    {
        $employee  = Employee::factory()->create();
        $data = Employee::factory()->make()->toArray();

        $response = $this->putJson("/employees/{$employee->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $employee->id]);
    }

    // ── DELETE /employees/{employee} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_employee(): void
    {
        $employee = Employee::factory()->create();

        $this->deleteJson("/employees/{$employee->id}")->assertOk();

        $this->assertDatabaseMissing((new Employee)->getTable(), ['id' => $employee->id]);
    }

}