<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Expired;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * ExpiredControllerTest
 *
 * Feature tests for ExpiredController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller ExpiredSchema --test
 */
class ExpiredControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /expireds ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Expired::factory()->create();
        Expired::factory()->create();

        $response = $this->getJson('/expireds');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /expireds ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_expired(): void
    {
        $data = Expired::factory()->make()->toArray();

        $response = $this->postJson('/expireds', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Expired)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/expireds', []);

        $response->assertUnprocessable();
    }

    // ── GET /expireds/{expired} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_expired(): void
    {
        $expired = Expired::factory()->create();

        $response = $this->getJson("/expireds/{$expired->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $expired->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_expired(): void
    {
        $this->getJson('/expireds/999999')->assertNotFound();
    }

    // ── PUT /expireds/{expired} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_expired(): void
    {
        $expired  = Expired::factory()->create();
        $data = Expired::factory()->make()->toArray();

        $response = $this->putJson("/expireds/{$expired->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $expired->id]);
    }

    // ── DELETE /expireds/{expired} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_expired(): void
    {
        $expired = Expired::factory()->create();

        $this->deleteJson("/expireds/{$expired->id}")->assertOk();

        $this->assertDatabaseMissing((new Expired)->getTable(), ['id' => $expired->id]);
    }

}