<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Favorite;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * FavoriteControllerTest
 *
 * Feature tests for FavoriteController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller FavoriteSchema --test
 */
class FavoriteControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /favorites ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Favorite::factory()->create();
        Favorite::factory()->create();

        $response = $this->getJson('/favorites');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /favorites ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_favorite(): void
    {
        $data = Favorite::factory()->make()->toArray();

        $response = $this->postJson('/favorites', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Favorite)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/favorites', []);

        $response->assertUnprocessable();
    }

    // ── GET /favorites/{favorite} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_favorite(): void
    {
        $favorite = Favorite::factory()->create();

        $response = $this->getJson("/favorites/{$favorite->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $favorite->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_favorite(): void
    {
        $this->getJson('/favorites/999999')->assertNotFound();
    }

    // ── PUT /favorites/{favorite} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_favorite(): void
    {
        $favorite  = Favorite::factory()->create();
        $data = Favorite::factory()->make()->toArray();

        $response = $this->putJson("/favorites/{$favorite->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $favorite->id]);
    }

    // ── DELETE /favorites/{favorite} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_favorite(): void
    {
        $favorite = Favorite::factory()->create();

        $this->deleteJson("/favorites/{$favorite->id}")->assertOk();

        $this->assertDatabaseMissing((new Favorite)->getTable(), ['id' => $favorite->id]);
    }

}