<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\History;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use PHPUnit\Framework\Attributes\Test;

/**
 * HistoryControllerTest
 *
 * Feature tests for HistoryController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller HistorySchema --test
 */
class HistoryControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /histories ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        History::factory()->create();
        History::factory()->create();

        $response = $this->getJson('/histories');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /histories ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_history(): void
    {
        $data = Arr::only(History::factory()->make()->toArray(), ['action', 'description']);

        $response = $this->postJson('/histories', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new History)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/histories', []);

        $response->assertUnprocessable();
    }

    // ── GET /histories/{history} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_history(): void
    {
        $history = History::factory()->create();

        $response = $this->getJson("/histories/{$history->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $history->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_history(): void
    {
        $this->getJson('/histories/999999')->assertNotFound();
    }

    // ── PUT /histories/{history} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_history(): void
    {
        $history  = History::factory()->create();
        $data = Arr::only(History::factory()->make()->toArray(), ['action', 'description']);

        $response = $this->putJson("/histories/{$history->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $history->id]);
    }

    // ── DELETE /histories/{history} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_history(): void
    {
        $history = History::factory()->create();

        $this->deleteJson("/histories/{$history->id}")->assertOk();

        $this->assertDatabaseMissing((new History)->getTable(), ['id' => $history->id]);
    }

}