<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Order;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * OrderControllerTest
 *
 * Feature tests for OrderController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller OrderSchema --test
 */
class OrderControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /orders ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Order::factory()->create();
        Order::factory()->create();

        $response = $this->getJson('/orders');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /orders ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_order(): void
    {
        $data = Order::factory()->make()->toArray();

        $response = $this->postJson('/orders', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Order)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/orders', []);

        $response->assertUnprocessable();
    }

    // ── GET /orders/{order} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_order(): void
    {
        $order = Order::factory()->create();

        $response = $this->getJson("/orders/{$order->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $order->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_order(): void
    {
        $this->getJson('/orders/999999')->assertNotFound();
    }

    // ── PUT /orders/{order} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_order(): void
    {
        $order  = Order::factory()->create();
        $data = Order::factory()->make()->toArray();

        $response = $this->putJson("/orders/{$order->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $order->id]);
    }

    // ── DELETE /orders/{order} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_order(): void
    {
        $order = Order::factory()->create();

        $this->deleteJson("/orders/{$order->id}")->assertOk();

        $this->assertDatabaseMissing((new Order)->getTable(), ['id' => $order->id]);
    }

}