<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Product;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * ProductControllerTest
 *
 * Feature tests for ProductController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller ProductSchema --test
 */
class ProductControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /products ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Product::factory()->create();
        Product::factory()->create();

        $response = $this->getJson('/products');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /products ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_product(): void
    {
        $data = Product::factory()->make()->toArray();

        $response = $this->postJson('/products', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Product)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/products', []);

        $response->assertUnprocessable();
    }

    // ── GET /products/{product} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_product(): void
    {
        $product = Product::factory()->create();

        $response = $this->getJson("/products/{$product->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $product->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_product(): void
    {
        $this->getJson('/products/999999')->assertNotFound();
    }

    // ── PUT /products/{product} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_product(): void
    {
        $product  = Product::factory()->create();
        $data = Product::factory()->make()->toArray();

        $response = $this->putJson("/products/{$product->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $product->id]);
    }

    // ── DELETE /products/{product} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_product(): void
    {
        $product = Product::factory()->create();

        $this->deleteJson("/products/{$product->id}")->assertOk();

        $this->assertDatabaseMissing((new Product)->getTable(), ['id' => $product->id]);
    }


    // ── Soft delete / restore ──────────────────────────────────────────────────

    #[Test]
    public function destroy_soft_deletes_a_product(): void
    {
        $product = Product::factory()->create();

        $this->deleteJson("/products/{$product->id}")->assertOk();

        $this->assertSoftDeleted((new Product)->getTable(), ['id' => $product->id]);
    }

    #[Test]
    public function restore_recovers_a_soft_deleted_product(): void
    {
        $product = Product::factory()->create();
        $product->delete();

        $this->patchJson("/products/restore/{$product->id}")->assertOk();

        $this->assertNotSoftDeleted((new Product)->getTable(), ['id' => $product->id]);
    }
}