<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Profile;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * ProfileControllerTest
 *
 * Feature tests for ProfileController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller ProfileSchema --test
 */
class ProfileControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /profiles ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Profile::factory()->create();
        Profile::factory()->create();

        $response = $this->getJson('/profiles');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /profiles ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_profile(): void
    {
        $data = Profile::factory()->make()->toArray();

        $response = $this->postJson('/profiles', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Profile)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/profiles', []);

        $response->assertUnprocessable();
    }

    // ── GET /profiles/{profile} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_profile(): void
    {
        $profile = Profile::factory()->create();

        $response = $this->getJson("/profiles/{$profile->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $profile->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_profile(): void
    {
        $this->getJson('/profiles/999999')->assertNotFound();
    }

    // ── PUT /profiles/{profile} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_profile(): void
    {
        $profile  = Profile::factory()->create();
        $data = Profile::factory()->make()->toArray();

        $response = $this->putJson("/profiles/{$profile->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $profile->id]);
    }

    // ── DELETE /profiles/{profile} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_profile(): void
    {
        $profile = Profile::factory()->create();

        $this->deleteJson("/profiles/{$profile->id}")->assertOk();

        $this->assertDatabaseMissing((new Profile)->getTable(), ['id' => $profile->id]);
    }

}