<?php

namespace Tests\Feature;

use App\Models\Role;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

/**
 * RoleControllerTest
 *
 * Feature tests for RoleController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller RoleSchema --test
 */
class RoleControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /roles ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Role::factory()->create();
        Role::factory()->create();

        $response = $this->getJson('/roles');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /roles ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_role(): void
    {
        $data = Arr::only(Role::factory()->make()->toArray(), ['public_id', 'name', 'status', 'age', 'born_at']);

        $response = $this->postJson('/roles', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Role)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/roles', []);

        $response->assertUnprocessable();
    }

    // ── GET /roles/{role} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_role(): void
    {
        $role = Role::factory()->create();

        $response = $this->getJson("/roles/{$role->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $role->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_role(): void
    {
        $this->getJson('/roles/999999')->assertNotFound();
    }

    // ── PUT /roles/{role} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_role(): void
    {
        $role = Role::factory()->create();
        $data = Arr::only(Role::factory()->make()->toArray(), ['public_id', 'name', 'status', 'age', 'born_at']);

        $response = $this->putJson("/roles/{$role->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $role->id]);
    }

    // ── DELETE /roles/{role} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_role(): void
    {
        $role = Role::factory()->create();

        $this->deleteJson("/roles/{$role->id}")->assertOk();

        $this->assertSoftDeleted((new Role)->getTable(), ['id' => $role->id]);
    }

    // ── Soft delete / restore ──────────────────────────────────────────────────

    #[Test]
    public function restore_recovers_a_soft_deleted_role(): void
    {
        $role = Role::factory()->create();
        $role->delete();

        $this->patchJson("/roles/restore/{$role->id}")->assertOk();

        $this->assertNotSoftDeleted((new Role)->getTable(), ['id' => $role->id]);
    }
}
