<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Setting;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * SettingControllerTest
 *
 * Feature tests for SettingController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller SettingSchema --test
 */
class SettingControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /settings ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Setting::factory()->create();
        Setting::factory()->create();

        $response = $this->getJson('/settings');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /settings ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_setting(): void
    {
        $data = Setting::factory()->make()->toArray();

        $response = $this->postJson('/settings', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Setting)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/settings', []);

        $response->assertUnprocessable();
    }

    // ── GET /settings/{setting} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_setting(): void
    {
        $setting = Setting::factory()->create();

        $response = $this->getJson("/settings/{$setting->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $setting->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_setting(): void
    {
        $this->getJson('/settings/999999')->assertNotFound();
    }

    // ── PUT /settings/{setting} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_setting(): void
    {
        $setting  = Setting::factory()->create();
        $data = Setting::factory()->make()->toArray();

        $response = $this->putJson("/settings/{$setting->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $setting->id]);
    }

    // ── DELETE /settings/{setting} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_setting(): void
    {
        $setting = Setting::factory()->create();

        $this->deleteJson("/settings/{$setting->id}")->assertOk();

        $this->assertDatabaseMissing((new Setting)->getTable(), ['id' => $setting->id]);
    }

}