<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Shop;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * ShopControllerTest
 *
 * Feature tests for ShopController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller ShopSchema --test
 */
class ShopControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /shops ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Shop::factory()->create();
        Shop::factory()->create();

        $response = $this->getJson('/shops');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /shops ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_shop(): void
    {
        $data = Shop::factory()->make()->toArray();

        $response = $this->postJson('/shops', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Shop)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/shops', []);

        $response->assertUnprocessable();
    }

    // ── GET /shops/{shop} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_shop(): void
    {
        $shop = Shop::factory()->create();

        $response = $this->getJson("/shops/{$shop->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $shop->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_shop(): void
    {
        $this->getJson('/shops/999999')->assertNotFound();
    }

    // ── PUT /shops/{shop} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_shop(): void
    {
        $shop  = Shop::factory()->create();
        $data = Shop::factory()->make()->toArray();

        $response = $this->putJson("/shops/{$shop->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $shop->id]);
    }

    // ── DELETE /shops/{shop} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_shop(): void
    {
        $shop = Shop::factory()->create();

        $this->deleteJson("/shops/{$shop->id}")->assertOk();

        $this->assertDatabaseMissing((new Shop)->getTable(), ['id' => $shop->id]);
    }


    // ── Soft delete / restore ──────────────────────────────────────────────────

    #[Test]
    public function destroy_soft_deletes_a_shop(): void
    {
        $shop = Shop::factory()->create();

        $this->deleteJson("/shops/{$shop->id}")->assertOk();

        $this->assertSoftDeleted((new Shop)->getTable(), ['id' => $shop->id]);
    }

    #[Test]
    public function restore_recovers_a_soft_deleted_shop(): void
    {
        $shop = Shop::factory()->create();
        $shop->delete();

        $this->patchJson("/shops/restore/{$shop->id}")->assertOk();

        $this->assertNotSoftDeleted((new Shop)->getTable(), ['id' => $shop->id]);
    }
}