<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Team;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * TeamControllerTest
 *
 * Feature tests for TeamController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller TeamSchema --test
 */
class TeamControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /teams ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Team::factory()->create();
        Team::factory()->create();

        $response = $this->getJson('/teams');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /teams ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_team(): void
    {
        $data = Team::factory()->make()->toArray();

        $response = $this->postJson('/teams', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Team)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/teams', []);

        $response->assertUnprocessable();
    }

    // ── GET /teams/{team} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_team(): void
    {
        $team = Team::factory()->create();

        $response = $this->getJson("/teams/{$team->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $team->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_team(): void
    {
        $this->getJson('/teams/999999')->assertNotFound();
    }

    // ── PUT /teams/{team} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_team(): void
    {
        $team  = Team::factory()->create();
        $data = Team::factory()->make()->toArray();

        $response = $this->putJson("/teams/{$team->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $team->id]);
    }

    // ── DELETE /teams/{team} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_team(): void
    {
        $team = Team::factory()->create();

        $this->deleteJson("/teams/{$team->id}")->assertOk();

        $this->assertDatabaseMissing((new Team)->getTable(), ['id' => $team->id]);
    }

}