<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Transaction;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * TransactionControllerTest
 *
 * Feature tests for TransactionController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller TransactionSchema --test
 */
class TransactionControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /transactions ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Transaction::factory()->create();
        Transaction::factory()->create();

        $response = $this->getJson('/transactions');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /transactions ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_transaction(): void
    {
        $data = Transaction::factory()->make()->toArray();

        $response = $this->postJson('/transactions', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Transaction)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/transactions', []);

        $response->assertUnprocessable();
    }

    // ── GET /transactions/{transaction} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_transaction(): void
    {
        $transaction = Transaction::factory()->create();

        $response = $this->getJson("/transactions/{$transaction->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $transaction->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_transaction(): void
    {
        $this->getJson('/transactions/999999')->assertNotFound();
    }

    // ── PUT /transactions/{transaction} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_transaction(): void
    {
        $transaction  = Transaction::factory()->create();
        $data = Transaction::factory()->make()->toArray();

        $response = $this->putJson("/transactions/{$transaction->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $transaction->id]);
    }

    // ── DELETE /transactions/{transaction} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_transaction(): void
    {
        $transaction = Transaction::factory()->create();

        $this->deleteJson("/transactions/{$transaction->id}")->assertOk();

        $this->assertDatabaseMissing((new Transaction)->getTable(), ['id' => $transaction->id]);
    }

}