<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\UserExample;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * UserExampleControllerTest
 *
 * Feature tests for UserExampleController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller UserExampleSchema --test
 */
class UserExampleControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /user_examples ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        UserExample::factory()->create();
        UserExample::factory()->create();

        $response = $this->getJson('/user_examples');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /user_examples ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_userExample(): void
    {
        $data = UserExample::factory()->make()->toArray();

        $response = $this->postJson('/user_examples', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new UserExample)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/user_examples', []);

        $response->assertUnprocessable();
    }

    // ── GET /user_examples/{userExample} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_userExample(): void
    {
        $userExample = UserExample::factory()->create();

        $response = $this->getJson("/user_examples/{$userExample->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $userExample->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_userExample(): void
    {
        $this->getJson('/user_examples/999999')->assertNotFound();
    }

    // ── PUT /user_examples/{userExample} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_userExample(): void
    {
        $userExample  = UserExample::factory()->create();
        $data = UserExample::factory()->make()->toArray();

        $response = $this->putJson("/user_examples/{$userExample->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $userExample->id]);
    }

    // ── DELETE /user_examples/{userExample} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_userExample(): void
    {
        $userExample = UserExample::factory()->create();

        $this->deleteJson("/user_examples/{$userExample->id}")->assertOk();

        $this->assertDatabaseMissing((new UserExample)->getTable(), ['id' => $userExample->id]);
    }


    // ── Soft delete / restore ──────────────────────────────────────────────────

    #[Test]
    public function destroy_soft_deletes_a_userExample(): void
    {
        $userExample = UserExample::factory()->create();

        $this->deleteJson("/user_examples/{$userExample->id}")->assertOk();

        $this->assertSoftDeleted((new UserExample)->getTable(), ['id' => $userExample->id]);
    }

    #[Test]
    public function restore_recovers_a_soft_deleted_userExample(): void
    {
        $userExample = UserExample::factory()->create();
        $userExample->delete();

        $this->patchJson("/user_examples/restore/{$userExample->id}")->assertOk();

        $this->assertNotSoftDeleted((new UserExample)->getTable(), ['id' => $userExample->id]);
    }
}