<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Warehouse;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;

/**
 * WarehouseControllerTest
 *
 * Feature tests for WarehouseController.
 * Tests every endpoint: index, store, show, update, destroy.
 * Generated by: php artisan schema:controller WarehouseSchema --test
 */
class WarehouseControllerTest extends TestCase
{
    use RefreshDatabase;

    // ── GET /warehouses ──────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Warehouse::factory()->create();
        Warehouse::factory()->create();

        $response = $this->getJson('/warehouses');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    // ── POST /warehouses ─────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_warehouse(): void
    {
        $data = Warehouse::factory()->make()->toArray();

        $response = $this->postJson('/warehouses', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Warehouse)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $response = $this->postJson('/warehouses', []);

        $response->assertUnprocessable();
    }

    // ── GET /warehouses/{warehouse} ──────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_single_warehouse(): void
    {
        $warehouse = Warehouse::factory()->create();

        $response = $this->getJson("/warehouses/{$warehouse->id}");

        $response->assertOk()
            ->assertJsonFragment(['id' => $warehouse->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_warehouse(): void
    {
        $this->getJson('/warehouses/999999')->assertNotFound();
    }

    // ── PUT /warehouses/{warehouse} ─────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_warehouse(): void
    {
        $warehouse  = Warehouse::factory()->create();
        $data = Warehouse::factory()->make()->toArray();

        $response = $this->putJson("/warehouses/{$warehouse->id}", $data);

        $response->assertOk()
            ->assertJsonFragment(['id' => $warehouse->id]);
    }

    // ── DELETE /warehouses/{warehouse} ──────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_warehouse(): void
    {
        $warehouse = Warehouse::factory()->create();

        $this->deleteJson("/warehouses/{$warehouse->id}")->assertOk();

        $this->assertDatabaseMissing((new Warehouse)->getTable(), ['id' => $warehouse->id]);
    }

}