<?php

namespace Tests\Feature\Api;

use Tests\TestCase;
use App\Models\Article;

use App\Models\Role;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use PHPUnit\Framework\Attributes\Test;

/**
 * ArticleControllerTest
 *
 * Feature/Api tests for ArticleController.
 * Generated by: php artisan schema:controller ArticleSchema --test
 */
class ArticleControllerTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Article::factory()->create();
        Article::factory()->create();

        $response = $this->getJson('/api/articles');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    #[Test]
    public function store_creates_a_new_article(): void
    {
        $role = Role::factory()->create();
        $data = Arr::only(Article::factory()->make()->toArray(), ['title', 'slug', 'content', 'excerpt', 'status', 'published_at']);
        $data['role_id'] = $role->id;

        $response = $this->postJson('/api/articles', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Article)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $this->postJson('/api/articles', [])->assertUnprocessable();
    }

    #[Test]
    public function show_returns_a_single_article(): void
    {
        $article = Article::factory()->create();

        $this->getJson("/api/articles/{$article->id}")
            ->assertOk()
            ->assertJsonFragment(['id' => $article->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_article(): void
    {
        $this->getJson('/api/articles/999999')->assertNotFound();
    }

    #[Test]
    public function update_modifies_an_existing_article(): void
    {
        $role = Role::factory()->create();
        $article = Article::factory()->create();
        $data   = Arr::only(Article::factory()->make()->toArray(), ['title', 'slug', 'content', 'excerpt', 'status', 'published_at']);
        $data['role_id'] = $role->id;

        $this->putJson("/api/articles/{$article->id}", $data)
            ->assertOk()
            ->assertJsonFragment(['id' => $article->id]);
    }

    #[Test]
    public function destroy_deletes_a_article(): void
    {
        $article = Article::factory()->create();

        $this->deleteJson("/api/articles/{$article->id}")->assertOk();

        $this->assertSoftDeleted((new Article)->getTable(), ['id' => $article->id]);
    }


    #[Test]
    public function restore_recovers_a_soft_deleted_article(): void
    {
        $article = Article::factory()->create();
        $article->delete();

        $this->patchJson("/api/articles/restore/{$article->id}")->assertOk();

        $this->assertNotSoftDeleted((new Article)->getTable(), ['id' => $article->id]);
    }
}