<?php

namespace Tests\Feature\Api;

use Tests\TestCase;
use App\Models\Department;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use PHPUnit\Framework\Attributes\Test;

/**
 * DepartmentControllerTest
 *
 * Feature/Api tests for DepartmentController.
 * Generated by: php artisan schema:controller DepartmentSchema --test
 */
class DepartmentControllerTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Department::factory()->create();
        Department::factory()->create();

        $response = $this->getJson('/api/departments');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    #[Test]
    public function store_creates_a_new_department(): void
    {
        $data = Arr::only(Department::factory()->make()->toArray(), ['name', 'code', 'slug', 'description', 'status', 'budget']);

        $response = $this->postJson('/api/departments', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Department)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $this->postJson('/api/departments', [])->assertUnprocessable();
    }

    #[Test]
    public function show_returns_a_single_department(): void
    {
        $department = Department::factory()->create();

        $this->getJson("/api/departments/{$department->id}")
            ->assertOk()
            ->assertJsonFragment(['id' => $department->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_department(): void
    {
        $this->getJson('/api/departments/999999')->assertNotFound();
    }

    #[Test]
    public function update_modifies_an_existing_department(): void
    {
        $department = Department::factory()->create();
        $data   = Arr::only(Department::factory()->make()->toArray(), ['name', 'code', 'slug', 'description', 'status', 'budget']);

        $this->putJson("/api/departments/{$department->id}", $data)
            ->assertOk()
            ->assertJsonFragment(['id' => $department->id]);
    }

    #[Test]
    public function destroy_deletes_a_department(): void
    {
        $department = Department::factory()->create();

        $this->deleteJson("/api/departments/{$department->id}")->assertOk();

        $this->assertDatabaseMissing((new Department)->getTable(), ['id' => $department->id]);
    }

}