<?php

namespace Tests\Feature\Api;

use Tests\TestCase;
use App\Models\Product;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use PHPUnit\Framework\Attributes\Test;

/**
 * ProductControllerTest
 *
 * Feature/Api tests for ProductController.
 * Generated by: php artisan schema:controller ProductSchema --test
 */
class ProductControllerTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Product::factory()->create();
        Product::factory()->create();

        $response = $this->getJson('/api/products');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    #[Test]
    public function store_creates_a_new_product(): void
    {
        $data = Arr::only(Product::factory()->make()->toArray(), ['name', 'description', 'price', 'stock', 'sku', 'status']);

        $response = $this->postJson('/api/products', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Product)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $this->postJson('/api/products', [])->assertUnprocessable();
    }

    #[Test]
    public function show_returns_a_single_product(): void
    {
        $product = Product::factory()->create();

        $this->getJson("/api/products/{$product->id}")
            ->assertOk()
            ->assertJsonFragment(['id' => $product->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_product(): void
    {
        $this->getJson('/api/products/999999')->assertNotFound();
    }

    #[Test]
    public function update_modifies_an_existing_product(): void
    {
        $product = Product::factory()->create();
        $data   = Arr::only(Product::factory()->make()->toArray(), ['name', 'description', 'price', 'stock', 'sku', 'status']);

        $this->putJson("/api/products/{$product->id}", $data)
            ->assertOk()
            ->assertJsonFragment(['id' => $product->id]);
    }

    #[Test]
    public function destroy_deletes_a_product(): void
    {
        $product = Product::factory()->create();

        $this->deleteJson("/api/products/{$product->id}")->assertOk();

        $this->assertDatabaseMissing((new Product)->getTable(), ['id' => $product->id]);
    }

}