<?php

namespace Tests\Feature\Api;

use Tests\TestCase;
use App\Models\Profile;

use App\Models\Role;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use PHPUnit\Framework\Attributes\Test;

/**
 * ProfileControllerTest
 *
 * Feature/Api tests for ProfileController.
 * Generated by: php artisan schema:controller ProfileSchema --test
 */
class ProfileControllerTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Profile::factory()->create();
        Profile::factory()->create();

        $response = $this->getJson('/api/profiles');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    #[Test]
    public function store_creates_a_new_profile(): void
    {
        $role = Role::factory()->create();
        $data = Arr::only(Profile::factory()->make()->toArray(), ['bio', 'avatar', 'phone', 'address', 'birth_date']);
        $data['role_id'] = $role->id;

        $response = $this->postJson('/api/profiles', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Profile)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $this->postJson('/api/profiles', [])->assertUnprocessable();
    }

    #[Test]
    public function show_returns_a_single_profile(): void
    {
        $profile = Profile::factory()->create();

        $this->getJson("/api/profiles/{$profile->id}")
            ->assertOk()
            ->assertJsonFragment(['id' => $profile->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_profile(): void
    {
        $this->getJson('/api/profiles/999999')->assertNotFound();
    }

    #[Test]
    public function update_modifies_an_existing_profile(): void
    {
        $role = Role::factory()->create();
        $profile = Profile::factory()->create();
        $data   = Arr::only(Profile::factory()->make()->toArray(), ['bio', 'avatar', 'phone', 'address', 'birth_date']);
        $data['role_id'] = $role->id;

        $this->putJson("/api/profiles/{$profile->id}", $data)
            ->assertOk()
            ->assertJsonFragment(['id' => $profile->id]);
    }

    #[Test]
    public function destroy_deletes_a_profile(): void
    {
        $profile = Profile::factory()->create();

        $this->deleteJson("/api/profiles/{$profile->id}")->assertOk();

        $this->assertDatabaseMissing((new Profile)->getTable(), ['id' => $profile->id]);
    }

}