<?php

namespace Tests\Feature\Api;

use Tests\TestCase;
use App\Models\Role;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use PHPUnit\Framework\Attributes\Test;

/**
 * RoleControllerTest
 *
 * Feature/Api tests for RoleController.
 * Generated by: php artisan schema:controller RoleSchema --test
 */
class RoleControllerTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Role::factory()->create();
        Role::factory()->create();

        $response = $this->getJson('/api/roles');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    #[Test]
    public function store_creates_a_new_role(): void
    {
        $data = Arr::only(Role::factory()->make()->toArray(), ['public_id', 'name', 'status', 'age', 'born_at']);

        $response = $this->postJson('/api/roles', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Role)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $this->postJson('/api/roles', [])->assertUnprocessable();
    }

    #[Test]
    public function show_returns_a_single_role(): void
    {
        $role = Role::factory()->create();

        $this->getJson("/api/roles/{$role->id}")
            ->assertOk()
            ->assertJsonFragment(['id' => $role->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_role(): void
    {
        $this->getJson('/api/roles/999999')->assertNotFound();
    }

    #[Test]
    public function update_modifies_an_existing_role(): void
    {
        $role = Role::factory()->create();
        $data   = Arr::only(Role::factory()->make()->toArray(), ['public_id', 'name', 'status', 'age', 'born_at']);

        $this->putJson("/api/roles/{$role->id}", $data)
            ->assertOk()
            ->assertJsonFragment(['id' => $role->id]);
    }

    #[Test]
    public function destroy_deletes_a_role(): void
    {
        $role = Role::factory()->create();

        $this->deleteJson("/api/roles/{$role->id}")->assertOk();

        $this->assertSoftDeleted((new Role)->getTable(), ['id' => $role->id]);
    }


    #[Test]
    public function restore_recovers_a_soft_deleted_role(): void
    {
        $role = Role::factory()->create();
        $role->delete();

        $this->patchJson("/api/roles/restore/{$role->id}")->assertOk();

        $this->assertNotSoftDeleted((new Role)->getTable(), ['id' => $role->id]);
    }
}