<?php

namespace Tests\Feature\Api;

use Tests\TestCase;
use App\Models\Team;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use PHPUnit\Framework\Attributes\Test;

/**
 * TeamControllerTest
 *
 * Feature/Api tests for TeamController.
 * Generated by: php artisan schema:controller TeamSchema --test
 */
class TeamControllerTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function index_returns_paginated_list(): void
    {
        Team::factory()->create();
        Team::factory()->create();

        $response = $this->getJson('/api/teams');

        $response->assertOk()
            ->assertJsonStructure(['data', 'total', 'per_page', 'current_page']);
    }

    #[Test]
    public function store_creates_a_new_team(): void
    {
        $data = Arr::only(Team::factory()->make()->toArray(), ['name', 'slug', 'description']);

        $response = $this->postJson('/api/teams', $data);

        $response->assertCreated()
            ->assertJsonFragment(['id' => $response->json('id')]);

        $this->assertDatabaseHas((new Team)->getTable(), ['id' => $response->json('id')]);
    }

    #[Test]
    public function store_fails_validation_with_empty_data(): void
    {
        $this->postJson('/api/teams', [])->assertUnprocessable();
    }

    #[Test]
    public function show_returns_a_single_team(): void
    {
        $team = Team::factory()->create();

        $this->getJson("/api/teams/{$team->id}")
            ->assertOk()
            ->assertJsonFragment(['id' => $team->id]);
    }

    #[Test]
    public function show_returns_404_for_missing_team(): void
    {
        $this->getJson('/api/teams/999999')->assertNotFound();
    }

    #[Test]
    public function update_modifies_an_existing_team(): void
    {
        $team = Team::factory()->create();
        $data   = Arr::only(Team::factory()->make()->toArray(), ['name', 'slug', 'description']);

        $this->putJson("/api/teams/{$team->id}", $data)
            ->assertOk()
            ->assertJsonFragment(['id' => $team->id]);
    }

    #[Test]
    public function destroy_deletes_a_team(): void
    {
        $team = Team::factory()->create();

        $this->deleteJson("/api/teams/{$team->id}")->assertOk();

        $this->assertDatabaseMissing((new Team)->getTable(), ['id' => $team->id]);
    }

}