<?php

namespace Tests\Unit;

use Tests\TestCase;
use App\Models\Article;
use App\Services\ArticleService;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use PHPUnit\Framework\Attributes\Test;

/**
 * ArticleServiceTest
 *
 * Unit tests for ArticleService.
 * Generated by: php artisan schema:service ArticleSchema --test
 */
class ArticleServiceTest extends TestCase
{
    use RefreshDatabase;

    // ── index ────────────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_results(): void
    {
        Article::factory()->create();
        Article::factory()->create();

        $result = ArticleService::index(new Request());

        $this->assertCount(2, $result);
    }

    // ── store ────────────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_article(): void
    {
        $data = Arr::only(Article::factory()->make()->toArray(), ['role_id', 'title', 'slug', 'content', 'excerpt', 'status', 'published_at']);

        $article = ArticleService::store($data);

        $this->assertInstanceOf(Article::class, $article);
        $this->assertDatabaseHas((new Article)->getTable(), ['id' => $article->id]);
    }

    // ── show ─────────────────────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_article_by_id(): void
    {
        $article = Article::factory()->create();

        $found = ArticleService::show($article->id);

        $this->assertTrue($article->is($found));
    }

    #[Test]
    public function show_throws_for_missing_article(): void
    {
        $this->expectException(\Illuminate\Database\Eloquent\ModelNotFoundException::class);

        ArticleService::show(999999);
    }

    // ── update ───────────────────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_article(): void
    {
        $article = Article::factory()->create();
        $data   = Arr::only(Article::factory()->make()->toArray(), ['role_id', 'title', 'slug', 'content', 'excerpt', 'status', 'published_at']);

        $updated = ArticleService::update($article, $data);

        $this->assertInstanceOf(Article::class, $updated);
        $this->assertEquals($article->id, $updated->id);
    }

    // ── destroy ──────────────────────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_article(): void
    {
        $article = Article::factory()->create();

        ArticleService::destroy($article);

        $this->assertSoftDeleted((new Article)->getTable(), ['id' => $article->id]);
    }


    // ── restore ──────────────────────────────────────────────────────────────

    #[Test]
    public function restore_recovers_a_soft_deleted_article(): void
    {
        $article = Article::factory()->create();
        $article->delete();

        $restored = ArticleService::restore($article->id);

        $this->assertNotSoftDeleted((new Article)->getTable(), ['id' => $article->id]);
        $this->assertTrue($article->is($restored));
    }
}