<?php

namespace Tests\Unit;

use Tests\TestCase;
use App\Models\Department;
use App\Services\DepartmentService;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use PHPUnit\Framework\Attributes\Test;

/**
 * DepartmentServiceTest
 *
 * Unit tests for DepartmentService.
 * Generated by: php artisan schema:service DepartmentSchema --test
 */
class DepartmentServiceTest extends TestCase
{
    use RefreshDatabase;

    // ── index ────────────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_results(): void
    {
        Department::factory()->create();
        Department::factory()->create();

        $result = DepartmentService::index(new Request());

        $this->assertCount(2, $result);
    }

    // ── store ────────────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_department(): void
    {
        $data = Arr::only(Department::factory()->make()->toArray(), ['name', 'code', 'slug', 'description', 'status', 'budget']);

        $department = DepartmentService::store($data);

        $this->assertInstanceOf(Department::class, $department);
        $this->assertDatabaseHas((new Department)->getTable(), ['id' => $department->id]);
    }

    // ── show ─────────────────────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_department_by_id(): void
    {
        $department = Department::factory()->create();

        $found = DepartmentService::show($department->id);

        $this->assertTrue($department->is($found));
    }

    #[Test]
    public function show_throws_for_missing_department(): void
    {
        $this->expectException(\Illuminate\Database\Eloquent\ModelNotFoundException::class);

        DepartmentService::show(999999);
    }

    // ── update ───────────────────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_department(): void
    {
        $department = Department::factory()->create();
        $data   = Arr::only(Department::factory()->make()->toArray(), ['name', 'code', 'slug', 'description', 'status', 'budget']);

        $updated = DepartmentService::update($department, $data);

        $this->assertInstanceOf(Department::class, $updated);
        $this->assertEquals($department->id, $updated->id);
    }

    // ── destroy ──────────────────────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_department(): void
    {
        $department = Department::factory()->create();

        DepartmentService::destroy($department);

        $this->assertDatabaseMissing((new Department)->getTable(), ['id' => $department->id]);
    }

}