<?php

namespace Tests\Unit;

use Tests\TestCase;
use App\Models\History;
use App\Services\HistoryService;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use PHPUnit\Framework\Attributes\Test;

/**
 * HistoryServiceTest
 *
 * Unit tests for HistoryService.
 * Generated by: php artisan schema:service HistorySchema --test
 */
class HistoryServiceTest extends TestCase
{
    use RefreshDatabase;

    // ── index ────────────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_results(): void
    {
        History::factory()->create();
        History::factory()->create();

        $result = HistoryService::index(new Request());

        $this->assertCount(2, $result);
    }

    // ── store ────────────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_history(): void
    {
        $data = Arr::only(History::factory()->make()->toArray(), ['action', 'description']);

        $history = HistoryService::store($data);

        $this->assertInstanceOf(History::class, $history);
        $this->assertDatabaseHas((new History)->getTable(), ['id' => $history->id]);
    }

    // ── show ─────────────────────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_history_by_id(): void
    {
        $history = History::factory()->create();

        $found = HistoryService::show($history->id);

        $this->assertTrue($history->is($found));
    }

    #[Test]
    public function show_throws_for_missing_history(): void
    {
        $this->expectException(\Illuminate\Database\Eloquent\ModelNotFoundException::class);

        HistoryService::show(999999);
    }

    // ── update ───────────────────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_history(): void
    {
        $history = History::factory()->create();
        $data   = Arr::only(History::factory()->make()->toArray(), ['action', 'description']);

        $updated = HistoryService::update($history, $data);

        $this->assertInstanceOf(History::class, $updated);
        $this->assertEquals($history->id, $updated->id);
    }

    // ── destroy ──────────────────────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_history(): void
    {
        $history = History::factory()->create();

        HistoryService::destroy($history);

        $this->assertDatabaseMissing((new History)->getTable(), ['id' => $history->id]);
    }

}