<?php

namespace Tests\Unit;

use Tests\TestCase;
use App\Models\Product;
use App\Services\ProductService;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use PHPUnit\Framework\Attributes\Test;

/**
 * ProductServiceTest
 *
 * Unit tests for ProductService.
 * Generated by: php artisan schema:service ProductSchema --test
 */
class ProductServiceTest extends TestCase
{
    use RefreshDatabase;

    // ── index ────────────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_results(): void
    {
        Product::factory()->create();
        Product::factory()->create();

        $result = ProductService::index(new Request());

        $this->assertCount(2, $result);
    }

    // ── store ────────────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_product(): void
    {
        $data = Product::factory()->raw();

        $product = ProductService::store($data);

        $this->assertInstanceOf(Product::class, $product);
        $this->assertDatabaseHas((new Product)->getTable(), ['id' => $product->id]);
    }

    // ── show ─────────────────────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_product_by_id(): void
    {
        $product = Product::factory()->create();

        $found = ProductService::show($product->id);

        $this->assertTrue($product->is($found));
    }

    #[Test]
    public function show_throws_for_missing_product(): void
    {
        $this->expectException(\Illuminate\Database\Eloquent\ModelNotFoundException::class);

        ProductService::show(999999);
    }

    // ── update ───────────────────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_product(): void
    {
        $product = Product::factory()->create();
        $data   = Product::factory()->raw();

        $updated = ProductService::update($product, $data);

        $this->assertInstanceOf(Product::class, $updated);
        $this->assertEquals($product->id, $updated->id);
    }

    // ── destroy ──────────────────────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_product(): void
    {
        $product = Product::factory()->create();

        ProductService::destroy($product);

        $this->assertDatabaseMissing((new Product)->getTable(), ['id' => $product->id]);
    }

}