<?php

namespace Tests\Unit;

use Tests\TestCase;
use App\Models\Profile;
use App\Services\ProfileService;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use PHPUnit\Framework\Attributes\Test;

/**
 * ProfileServiceTest
 *
 * Unit tests for ProfileService.
 * Generated by: php artisan schema:service ProfileSchema --test
 */
class ProfileServiceTest extends TestCase
{
    use RefreshDatabase;

    // ── index ────────────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_results(): void
    {
        Profile::factory()->create();
        Profile::factory()->create();

        $result = ProfileService::index(new Request());

        $this->assertCount(2, $result);
    }

    // ── store ────────────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_profile(): void
    {
        $data = Arr::only(Profile::factory()->make()->toArray(), ['role_id', 'bio', 'avatar', 'phone', 'address', 'birth_date']);

        $profile = ProfileService::store($data);

        $this->assertInstanceOf(Profile::class, $profile);
        $this->assertDatabaseHas((new Profile)->getTable(), ['id' => $profile->id]);
    }

    // ── show ─────────────────────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_profile_by_id(): void
    {
        $profile = Profile::factory()->create();

        $found = ProfileService::show($profile->id);

        $this->assertTrue($profile->is($found));
    }

    #[Test]
    public function show_throws_for_missing_profile(): void
    {
        $this->expectException(\Illuminate\Database\Eloquent\ModelNotFoundException::class);

        ProfileService::show(999999);
    }

    // ── update ───────────────────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_profile(): void
    {
        $profile = Profile::factory()->create();
        $data   = Arr::only(Profile::factory()->make()->toArray(), ['role_id', 'bio', 'avatar', 'phone', 'address', 'birth_date']);

        $updated = ProfileService::update($profile, $data);

        $this->assertInstanceOf(Profile::class, $updated);
        $this->assertEquals($profile->id, $updated->id);
    }

    // ── destroy ──────────────────────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_profile(): void
    {
        $profile = Profile::factory()->create();

        ProfileService::destroy($profile);

        $this->assertDatabaseMissing((new Profile)->getTable(), ['id' => $profile->id]);
    }

}