<?php

namespace Tests\Unit;

use Tests\TestCase;
use App\Models\Role;
use App\Services\RoleService;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use PHPUnit\Framework\Attributes\Test;

/**
 * RoleServiceTest
 *
 * Unit tests for RoleService.
 * Generated by: php artisan schema:service RoleSchema --test
 */
class RoleServiceTest extends TestCase
{
    use RefreshDatabase;

    // ── index ────────────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_results(): void
    {
        Role::factory()->create();
        Role::factory()->create();

        $result = RoleService::index(new Request());

        $this->assertCount(2, $result);
    }

    // ── store ────────────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_role(): void
    {
        $data = Arr::only(Role::factory()->make()->toArray(), ['public_id', 'name', 'status', 'age', 'born_at', 'department_id']);

        $role = RoleService::store($data);

        $this->assertInstanceOf(Role::class, $role);
        $this->assertDatabaseHas((new Role)->getTable(), ['id' => $role->id]);
    }

    // ── show ─────────────────────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_role_by_id(): void
    {
        $role = Role::factory()->create();

        $found = RoleService::show($role->id);

        $this->assertTrue($role->is($found));
    }

    #[Test]
    public function show_throws_for_missing_role(): void
    {
        $this->expectException(\Illuminate\Database\Eloquent\ModelNotFoundException::class);

        RoleService::show(999999);
    }

    // ── update ───────────────────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_role(): void
    {
        $role = Role::factory()->create();
        $data   = Arr::only(Role::factory()->make()->toArray(), ['public_id', 'name', 'status', 'age', 'born_at', 'department_id']);

        $updated = RoleService::update($role, $data);

        $this->assertInstanceOf(Role::class, $updated);
        $this->assertEquals($role->id, $updated->id);
    }

    // ── destroy ──────────────────────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_role(): void
    {
        $role = Role::factory()->create();

        RoleService::destroy($role);

        $this->assertSoftDeleted((new Role)->getTable(), ['id' => $role->id]);
    }


    // ── restore ──────────────────────────────────────────────────────────────

    #[Test]
    public function restore_recovers_a_soft_deleted_role(): void
    {
        $role = Role::factory()->create();
        $role->delete();

        $restored = RoleService::restore($role->id);

        $this->assertNotSoftDeleted((new Role)->getTable(), ['id' => $role->id]);
        $this->assertTrue($role->is($restored));
    }
}