<?php

namespace Tests\Unit;

use Tests\TestCase;
use App\Models\Team;
use App\Services\TeamService;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use PHPUnit\Framework\Attributes\Test;

/**
 * TeamServiceTest
 *
 * Unit tests for TeamService.
 * Generated by: php artisan schema:service TeamSchema --test
 */
class TeamServiceTest extends TestCase
{
    use RefreshDatabase;

    // ── index ────────────────────────────────────────────────────────────────

    #[Test]
    public function index_returns_paginated_results(): void
    {
        Team::factory()->create();
        Team::factory()->create();

        $result = TeamService::index(new Request());

        $this->assertCount(2, $result);
    }

    // ── store ────────────────────────────────────────────────────────────────

    #[Test]
    public function store_creates_a_new_team(): void
    {
        $data = Arr::only(Team::factory()->make()->toArray(), ['name', 'slug', 'description']);

        $team = TeamService::store($data);

        $this->assertInstanceOf(Team::class, $team);
        $this->assertDatabaseHas((new Team)->getTable(), ['id' => $team->id]);
    }

    // ── show ─────────────────────────────────────────────────────────────────

    #[Test]
    public function show_returns_a_team_by_id(): void
    {
        $team = Team::factory()->create();

        $found = TeamService::show($team->id);

        $this->assertTrue($team->is($found));
    }

    #[Test]
    public function show_throws_for_missing_team(): void
    {
        $this->expectException(\Illuminate\Database\Eloquent\ModelNotFoundException::class);

        TeamService::show(999999);
    }

    // ── update ───────────────────────────────────────────────────────────────

    #[Test]
    public function update_modifies_an_existing_team(): void
    {
        $team = Team::factory()->create();
        $data   = Arr::only(Team::factory()->make()->toArray(), ['name', 'slug', 'description']);

        $updated = TeamService::update($team, $data);

        $this->assertInstanceOf(Team::class, $updated);
        $this->assertEquals($team->id, $updated->id);
    }

    // ── destroy ──────────────────────────────────────────────────────────────

    #[Test]
    public function destroy_deletes_a_team(): void
    {
        $team = Team::factory()->create();

        TeamService::destroy($team);

        $this->assertDatabaseMissing((new Team)->getTable(), ['id' => $team->id]);
    }

}